# Workflow derived from https://github.com/r-lib/actions/tree/master/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
name: Generate A New Vintage

on:
  # Every Week Friday at 1:15 AM
  schedule:
    - cron: '15 1 * * 5'

  # Optional Workflow Dispatch Trigger
  workflow_dispatch:

jobs:
  GenerateNewVintage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
      # https://blog--simonpcouch.netlify.app/blog/r-github-actions-commit/
      - name: Install Dependencies
        run: |
          options(repos = c(CRAN = "https://cloud.r-project.org"))
          install.packages(c("fastverse", "DBI", "RMySQL", "writexl", "seasonal"))
          install.packages("https://www.dropbox.com/s/j4s98y7wknzcaww/samadb_0.2.5.tar.gz?dl=1", repos = NULL, type = "source")
          library(fastverse)
          fastverse_extend(samadb, seasonal, writexl, install = TRUE)
        shell: Rscript {0}
      - name: Generate Vintage
        run: Rscript ./code/nowcast_data_econdata_clean.R
      # Commit all changed files back to the repository
      - uses: stefanzweifel/git-auto-commit-action@v4
